name: 'Cut a Release Candidate'
description: 'Cut a release candidate branch'
inputs:
  version:
    description: 'Version of the package to publish'
    required: true
  commit_id:
    description: 'Commit ID for cut'
    required: false
    default: 'origin/main'
  client_python_commit_id:
    description: 'llama-stack-client-python commit ID for "cut"'
    required: false
    default: 'origin/main'
  cut_mode:
    description: 'Mode to run the script in (test-and-cut, test-only, cut-only)'
    required: false
    default: 'test-and-cut'
  template:
    description: '--stack-config for testing'
    required: false
    default: 'fireworks'
  llama_stack_only:
    description: 'Only cut a llama-stack release candidate'
    required: false
    default: 'false'
  fireworks_api_key:
    description: 'Fireworks API key'
    required: true
  together_api_key:
    description: 'Together API key'
    required: true
  tavily_search_api_key:
    description: 'Tavily Search API key'
    required: true
  github_token:
    description: 'Personal Access Token (PAT) with access to all llama repositories'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        enable-cache: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y bubblewrap

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build and publish
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        COMMIT_ID: ${{ inputs.commit_id }}
        CLIENT_PYTHON_COMMIT_ID: ${{ inputs.client_python_commit_id }}
        TEMPLATE: ${{ inputs.template }}
        CUT_MODE: ${{ inputs.cut_mode }}
        LLAMA_STACK_ONLY: ${{ inputs.llama_stack_only }}
        TOGETHER_API_KEY: ${{ inputs.together_api_key }}
        TAVILY_SEARCH_API_KEY: ${{ inputs.tavily_search_api_key }}
        FIREWORKS_API_KEY: ${{ inputs.fireworks_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        chmod +x ${{ github.action_path }}/main.sh
        ${{ github.action_path }}/main.sh
