name: Nightly Build and Publish

on:
#  schedule:
#    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to auto-generate nightly version from release version)'
        required: false
        type: string

jobs:
  nightly:
    runs-on: ubuntu-latest
    environment:
      name: testrelease
    permissions:
      id-token: write  # Required for trusted publishing to PyPI/TestPyPI
      contents: read
    steps:
    - uses: actions/checkout@v4

    - uses: ./actions/nightly-build-publish
      with:
        version: ${{ inputs.version }}
        llama_stack_only: false
        github_token: ${{ secrets.LLAMA_REPOS_PAT }}
        npm_token: ${{ secrets.NPM_TOKEN }}
        together_api_key: ${{ secrets.TOGETHER_API_KEY }}
        fireworks_api_key: ${{ secrets.FIREWORKS_API_KEY }}
        tavily_search_api_key: ${{ secrets.TAVILY_SEARCH_API_KEY }}
